version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./server/src:/app/src
    environment:
      - NODE_ENV=development
    ports:
      - '9229:9229'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 350M
